signing:
  active: RELEASE
  pgp:
    active: RELEASE
    armored: true

release:
  github:
    enabled: true
    skipTag: true
    skipRelease: true

deploy:
  maven:
    mavenCentral:
      sonatype:
        active: RELEASE
        url: https://central.sonatype.com/api/v1/publisher
        namespace: io.github.ggomarighetti
        applyMavenCentralRules: true
        stagingRepositories:
          - target/staging-deploy
